-- Auto-generated from schema-map-postgres.yaml (map@sha1:621FDD3D99B768B6A8AD92061FB029414184F4B3)
-- engine: postgres
-- table:  orders

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  uuid CHAR(36) NOT NULL UNIQUE,
  uuid_bin BYTEA NULL,
  public_order_no VARCHAR(64) NULL,
  user_id BIGINT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  encrypted_customer_blob BYTEA NULL,
  encrypted_customer_blob_key_version VARCHAR(64) NULL,
  encryption_meta JSONB NULL,
  currency CHAR(3) NOT NULL,
  metadata JSONB NULL,
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  payment_method VARCHAR(100) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_orders_version CHECK (version >= 0),
  CONSTRAINT chk_orders_status CHECK (status IN ('pending','paid','failed','cancelled','refunded','completed')),
  CONSTRAINT chk_orders_currency CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT chk_orders_nonneg CHECK (subtotal >= 0 AND discount_total >= 0 AND tax_total >= 0 AND total >= 0),
  CONSTRAINT chk_orders_total_eq CHECK (total = subtotal - discount_total + tax_total)
);
