-- Auto-generated from schema-map-postgres.psd1 (map@mtime:2025-10-24T09:46:38Z)
-- engine: postgres
-- table:  orders
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid CHAR(36) NOT NULL UNIQUE,
  uuid_bin BYTEA NULL,
  public_order_no VARCHAR(64) NULL,
  user_id BIGINT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  encrypted_customer_blob BYTEA NULL,
  encrypted_customer_blob_key_version VARCHAR(64) NULL,
  encryption_meta JSONB NULL,
  currency CHAR(3) NOT NULL,
  metadata JSONB NULL,
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  payment_method VARCHAR(100) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_orders_status CHECK (status IN ('pending','paid','failed','cancelled','refunded','completed')),
  CONSTRAINT chk_orders_currency CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT ux_orders_uuid_bin UNIQUE (uuid_bin)
);
